// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/games": {
            "post": {
                "description": "Create a new game room, optionally private or public for matchmaking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Create a new game",
                "parameters": [
                    {
                        "description": "Game configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.CreateGameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.CreateGameResponse"
                        }
                    }
                }
            }
        },
        "/games/join": {
            "post": {
                "description": "Join a game by room ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Join an existing game",
                "parameters": [
                    {
                        "description": "Join parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.JoinGameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.JoinGameResponse"
                        }
                    }
                }
            }
        },
        "/games/{gameID}": {
            "get": {
                "description": "Get current game state",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Get game state",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID (Room ID)",
                        "name": "gameID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Room"
                        }
                    }
                }
            }
        },
        "/games/{gameID}/players/{playerID}/pin": {
            "post": {
                "description": "Select pins for all rounds of the game",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Select pins for the game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID (Room ID)",
                        "name": "gameID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Player ID",
                        "name": "playerID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Selected pins",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.SelectPinRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.SelectPinResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the server is healthy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "server.CreateGameRequest": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/store.GameConfig"
                },
                "player_name": {
                    "type": "string"
                }
            }
        },
        "server.CreateGameResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/store.GameConfig"
                },
                "player_id": {
                    "type": "string"
                },
                "room_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "server.JoinGameRequest": {
            "type": "object",
            "properties": {
                "player_name": {
                    "type": "string"
                },
                "room_id": {
                    "type": "string"
                }
            }
        },
        "server.JoinGameResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/store.GameConfig"
                },
                "player_id": {
                    "type": "string"
                },
                "room_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "server.SelectPinRequest": {
            "type": "object",
            "properties": {
                "pins": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "server.SelectPinResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "store.GameConfig": {
            "type": "object",
            "properties": {
                "hints_enabled": {
                    "type": "boolean"
                },
                "is_private": {
                    "type": "boolean"
                },
                "pin_length": {
                    "type": "integer"
                },
                "player_name": {
                    "type": "string"
                },
                "timer_duration": {
                    "description": "0 means no timer",
                    "type": "integer"
                }
            }
        },
        "store.Room": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/store.GameConfig"
                },
                "created_at": {
                    "type": "string"
                },
                "current_round": {
                    "description": "1-indexed (1, 2, 3)",
                    "type": "integer"
                },
                "host_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ready_players": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scores": {
                    "description": "PlayerID -\u003e Score (Rounds won)",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "status": {
                    "description": "e.g., \"waiting\", \"playing\", \"finished\"",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8103",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Lockpick API",
	Description:      "API for Lockpick game.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
